services:
  - type: web
    name: liveesh-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build:api
    startCommand: npm run api:start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://liveesh.vercel.app
      # - key: PORT
      #   value: $PORT
