import type { WallpaperStore, WallpaperSettings } from './../src/types/fluidMesh.ts'
import express from 'express';
import cors from 'cors'
import dotenv from 'dotenv'
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import { fileURLToPath } from 'url'

dotenv.config()

const app = express()
const port = Number(process.env.PORT)
if(!port) throw new Error('PORT environment variable is required by Render')

// Resolve __dirname in ES modules
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Data store setup
const dataDir = path.join(__dirname, 'data')
const dataFile = path.join(dataDir, 'wallpapers.json')

const ensureStore = () => {
  if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true })
  if (!fs.existsSync(dataFile)) fs.writeFileSync(dataFile, JSON.stringify({ items: {} }, null, 2))
}

const readStore = (): WallpaperStore => {
  ensureStore()
  try {
    return JSON.parse(fs.readFileSync(dataFile, 'utf-8'))
  } catch (err) {
    console.log(err)
    return { items: {} }
  }
}

const writeStore = (store: WallpaperStore) => {
  fs.writeFileSync(dataFile, JSON.stringify(store, null, 2))
}

// CORS setup
const corsOrigins = (process.env.CORS_ORIGINS || 'http://localhost:5173')
  .split(',')
  .map((o) => o.trim())
  .filter(Boolean)

const isAllowedOrigin = (origin: string | undefined) => {
  if (!origin) return true
  if (corsOrigins.includes(origin)) return true
  if (origin.startsWith('http://localhost:') || origin.startsWith('http://127.0.0.1:')) return true
  return false
}

app.use(cors({ 
  origin: (origin, callback) => isAllowedOrigin(origin) ? callback(null, true) : callback(new Error('Not allowed by CORS')) 
}))

app.use(express.json({ limit: '1mb' }))

// --- API Routes ---

app.get('/api/health', (_req, res) => res.json({ status: 'ok' }))

// Create wallpaper
app.post('/api/wallpapers', (req, res) => {
  const settings: WallpaperSettings = req.body?.settings
  if (!settings) return res.status(400).json({ error: 'Missing settings' })

  const store = readStore()
  const id = crypto.randomUUID()

  store.items[id] = { id, settings, createdAt: new Date().toISOString() }
  writeStore(store)

  res.json({ id })
})

// Get wallpaper by ID
app.get('/api/wallpapers/:id', (req, res) => {
  const store = readStore()
  const record = store.items?.[req.params.id]
  if (!record) return res.status(404).json({ error: 'Not found' })
  res.json(record)
})

// --- Embed Link Helper for Tauri ---
// --- Embed Link Helper for Tauri ---
app.get('/embed/:id', (req, res) => {
  const store = readStore()
  const record = store.items?.[req.params.id]

  if (!record) return res.status(404).send('Wallpaper not found.')

  let embedUrl = `http://localhost:${port}/embed/${req.params.id}`

  // Auto-detect Tauri mode: either env variable or running via npm dev:tauri
  const isTauri = !!process.env.TAURI_PLATFORM || process.env.npm_lifecycle_event === 'dev:tauri'
  if (isTauri) {
    embedUrl = `liveesh://embed/${req.params.id}`
  }

  res.send(`
    <html>
      <body style="background: #f6f3ef; font-family: sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0;">
        <div style="padding: 2rem; background: white; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          <p>Embed URL: <code>${embedUrl}</code></p>
        </div>
      </body>
    </html>
  `)
})
// --- Serve SPA + static files ---

// IMPORTANT: Point to the 'dist' folder generated by 'npm run build'
const distDir = path.resolve(__dirname, '..', 'dist')

if (fs.existsSync(distDir)) {
  app.use(express.static(distDir))
  app.get(/^(?!\/api).+/, (_req, res) => {
    res.sendFile(path.join(distDir, 'index.html'))
  })
} else {
  console.log('⚠️  Dist directory not found. Run "npm run build" first to serve the frontend.')
}

// --- Start server ---
app.listen(port, () => {
  console.log(`🚀 Wallpaper API running on ${port}`)
})